name: Gerrit Group ownership
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - env:
          PYTHONUNBUFFERED: "true"
          PYTHONDONTWRITEBYTECODE: "true"
          GERRIT_USER: ${{ secrets.GERRIT_USER }}
          GERRIT_PASS: ${{ secrets.GERRIT_PASS }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          LOG_LEVEL: ${{ github.event.input.logLevel }}
        run: |
          pip install -r requirements.txt
          python test.py
          python cron_group_ownership.py
      - name: notify discord on failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE: "A job has failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          pip install -r requirements.txt
          python discord.py
